### PR TITLE
Fix #74, #75, #76, #84

### LINKED ISSUE #74: [New IoT Edge solution] if input module name is  /Sample/Module/, will get error
if input module name is  /Sample/Module/, will get error : 
Command failed with exit code 214750003

### PR DESCRIPTION
**Pull request by formulahendry**

### CODE REVIEW

File: src/edge/edgeManager.ts [hunk 1]
```diff
@@ -232,21 +234,23 @@ export class EdgeManager {
...
         }
-    }
-
-    private async validateModuleName(existingModules: string[], moduleName: string): Promise<string | undefined> {
-        if (existingModules.indexOf(moduleName) > -1) {
-            return `Module '${moduleName}' already exists`;
-        } else {
-            return undefined;
+        if (name.startsWith("_") || name.endsWith("_")) {
+            return "The name must not start or end with the symbol _";
```
Comment (adashen) [inline src/edge/edgeManager.ts]: is "_" not allowed in project name?
